# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


cities = City.create([
                         {id: 2, name: 'BEIJING'},
                         {id: 13, name: 'BRUSSELS'},
                         {id: 6, name: 'GENEVA'},
                         {id: 14, name: 'HONG KONG'},
                         {id: 10, name: 'LONDON'},
                         {id: 17, name: 'LOS ANGELES'},
                         {id: 4, name: 'MOSCOW'},
                         {id: 1, name: 'NEW YORK CITY'},
                         {id: 12, name: 'NICE'},
                         {id: 9, name: 'PARIS'},
                         {id: 16, name: 'SAN DIEGO'},
                         {id: 15, name: 'SAN FRANCISCO'},
                         {id: 11, name: 'SHANGHAI'},
                         {id: 8, name: 'ST PETERSBURG'},
                         {id: 7, name: 'WASHINGTON D.C'}]
)

puts "#{cities.count} cities created"


brands = Brand.create!([
                           {id: 14, name: 'BOTTEGA VENETA'},
                           {id: 15, name: 'BURBERRY'},
                           {id: 19, name: 'CHANEL'},
                           {id: 11, name: 'CHLOE'},
                           {id: 4, name: 'CHOPARD'},
                           {id: 16, name: 'DIOR'},
                           {id: 13, name: 'FENDI'},
                           {id: 12, name: 'GUCCI'},
                           {id: 1, name: 'HERMES'},
                           {id: 3, name: 'HUBLOT'},
                           {id: 7, name: 'LONGINES'},
                           {id: 20, name: 'LOUIS VUITTON'},
                           {id: 18, name: 'MIU MIU'},
                           {id: 5, name: 'OMEGA'},
                           {id: 17, name: 'PRADA'},
                           {id: 9, name: 'RADO'},
                           {id: 2, name: 'ROLEX'},
                           {id: 21, name: 'SALVATORE FERRAGAMO'},
                           {id: 6, name: 'TAG HEUER'},
                           {id: 8, name: 'TISSOT'}
                       ])


puts "#{brands.count} brands created"


categories = Category.create!([
                                  {id: 8, name: 'Decorative Object'},
                                  {id: 9, name: 'Fashion Accessory'},
                                  {id: 2, name: 'Jewellery'},
                                  {id: 1, name: 'Leather Good'},
                                  {id: 3, name: 'Watch'}
                              ])

puts "#{categories.count} categories created"

products = Product.create!([
                               {id: 78, name: 'Drew leather shoulder bag', brand_id: 11, category_id: 1},
                               {id: 60, name: 'Saint-Imier Date 38,5 mm', brand_id: 7, category_id: 3},
                               {id: 85, name: 'Lady Dior ', brand_id: 16, category_id: 1},
                               {id: 56, name: 'Coupole M', brand_id: 9, category_id: 3},
                               {id: 58, name: 'Conquest', brand_id: 7, category_id: 3},
                               {id: 84, name: 'Lady dior ', brand_id: 16, category_id: 1},
                               {id: 82, name: 'Lady Dior ', brand_id: 16, category_id: 1},
                               {id: 86, name: 'Lockit MM', brand_id: 20, category_id: 1},
                               {id: 3, name: 'Jypsière - PM', brand_id: 1, category_id: 1},
                               {id: 59, name: 'Master Collection Chronograph', brand_id: 7, category_id: 3},
                               {id: 83, name: 'Lady dior ', brand_id: 16, category_id: 1},
                               {id: 69, name: 'Sac roma new chartreuse en veau léger intrecciato', brand_id: 14, category_id: 1},
                               {id: 70, name: 'Nero intrecciato light calf roma', brand_id: 14, category_id: 1},
                               {id: 51, name: 'Speedmaster Chronograph 38 mm', brand_id: 5, category_id: 3},
                               {id: 89, name: 'CAPUCINES MM', brand_id: 20, category_id: 1},
                               {id: 79, name: 'Paraty Indian Summer', brand_id: 11, category_id: 1},
                               {id: 52, name: 'Seamaster Diver 41 mm', brand_id: 5, category_id: 3},
                               {id: 13, name: 'Datejust', brand_id: 2, category_id: 3},
                               {id: 71, name: 'Nero intrecciato nappa tote', brand_id: 14, category_id: 1},
                               {id: 64, name: 'Large Peekaboo', brand_id: 13, category_id: 1},
                               {id: 87, name: 'Lockit PM', brand_id: 20, category_id: 1},
                               {id: 88, name: 'Chain Louise', brand_id: 20, category_id: 1},
                               {id: 66, name: 'Double Sens', brand_id: 1, category_id: 1},
                               {id: 11, name: 'Soya', brand_id: 1, category_id: 9},
                               {id: 32, name: 'Constellation ', brand_id: 5, category_id: 3},
                               {id: 67, name: 'Garden Party', brand_id: 1, category_id: 1},
                               {id: 65, name: 'Evelyne III', brand_id: 1, category_id: 1},
                               {id: 33, name: 'Master Collection', brand_id: 7, category_id: 3},
                               {id: 14, name: 'Big Bang Steel', brand_id: 3, category_id: 3},
                               {id: 63, name: 'Large Peekaboo', brand_id: 13, category_id: 1},
                               {id: 17, name: 'Carrera for Woman', brand_id: 6, category_id: 3},
                               {id: 72, name: 'The small bloomsbury in grainy leather', brand_id: 15, category_id: 1},
                               {id: 41, name: 'De Ville Prestige 36,8 mm', brand_id: 5, category_id: 3},
                               {id: 90, name: 'Sofia', brand_id: 21, category_id: 1},
                               {id: 18, name: 'Carrera for Man', brand_id: 6, category_id: 3},
                               {id: 34, name: 'Saint-Imier Date 30 mm', brand_id: 7, category_id: 3},
                               {id: 35, name: 'Evidenza', brand_id: 7, category_id: 3},
                               {id: 30, name: 'De Ville Prestige 39,5 mm -  Steel on Leather Strap', brand_id: 5, category_id: 3},
                               {id: 23, name: 'Double Sens', brand_id: 1, category_id: 1},
                               {id: 91, name: 'Lady Dior ', brand_id: 16, category_id: 1},
                               {id: 20, name: 'Jypsière', brand_id: 1, category_id: 1},
                               {id: 28, name: 'De Ville 41 mm', brand_id: 5, category_id: 3},
                               {id: 29, name: 'De Ville Prestige 36,8 mm - Steel on Steel', brand_id: 5, category_id: 3},
                               {id: 24, name: 'Garden', brand_id: 1, category_id: 1},
                               {id: 8, name: 'Chaîne d\'Ancre Necklace - GM', brand_id: 1, category_id: 2},
                               {id: 9, name: 'Cape Cod - PM', brand_id: 1, category_id: 3},
                               {id: 10, name: 'Aligator Noble Gloves - Man', brand_id: 1, category_id: 9},
                               {id: 21, name: 'Double Sens', brand_id: 1, category_id: 1},
                               {id: 12, name: 'Collier de Chien ', brand_id: 1, category_id: 9},
                               {id: 7, name: 'Cigar Case', brand_id: 1, category_id: 8},
                               {id: 54, name: 'Centrix S', brand_id: 9, category_id: 3},
                               {id: 55, name: 'Centrix S ', brand_id: 9, category_id: 3},
                               {id: 50, name: 'De Ville Prestige 39,5 mm -  Steel on Leather Strap', brand_id: 5, category_id: 3},
                               {id: 46, name: 'De Ville Ladymatic 34 mm', brand_id: 5, category_id: 3},
                               {id: 31, name: 'De Ville Prestige 39,5 mm', brand_id: 5, category_id: 3},
                               {id: 48, name: 'Seamaster Diver Chronograph 41,5 mm', brand_id: 5, category_id: 3},
                               {id: 49, name: 'Speedmaster 38 mm', brand_id: 5, category_id: 3},
                               {id: 44, name: 'Constellation Quartz 24 mm', brand_id: 5, category_id: 3},
                               {id: 45, name: 'De Ville Ladymatic 34 mm', brand_id: 5, category_id: 3},
                               {id: 43, name: 'De Ville Prestige 36,8 mm', brand_id: 5, category_id: 3},
                               {id: 42, name: 'Constellation Quartz 24 mm mother-of-pearl', brand_id: 5, category_id: 3},
                               {id: 40, name: 'Luxury Automatic Lady Cosc', brand_id: 8, category_id: 3},
                               {id: 38, name: 'Centrix L', brand_id: 9, category_id: 3},
                               {id: 36, name: 'Le Locle Automatic gent Cosc', brand_id: 8, category_id: 3},
                               {id: 37, name: 'Hyperchrome', brand_id: 9, category_id: 3},
                               {id: 39, name: 'True', brand_id: 9, category_id: 3},
                               {id: 47, name: 'De Ville Ladymatic 34 mm', brand_id: 5, category_id: 3},
                               {id: 26, name: 'De Ville Prestige 39.5 mm', brand_id: 5, category_id: 3},
                               {id: 57, name: 'Centrix L Steel', brand_id: 9, category_id: 3},
                               {id: 22, name: 'Double Sens', brand_id: 1, category_id: 1},
                               {id: 6, name: 'Calèche Luggage - PM', brand_id: 1, category_id: 1},
                               {id: 5, name: 'Double Sens', brand_id: 1, category_id: 1},
                               {id: 4, name: 'Garden', brand_id: 1, category_id: 1},
                               {id: 15, name: 'Happy Sport Medium', brand_id: 4, category_id: 3},
                               {id: 19, name: 'Jypsière - GM', brand_id: 1, category_id: 1},
                               {id: 68, name: 'New chartreuse intrecciato light calf roma', brand_id: 14, category_id: 1},
                               {id: 77, name: 'Tote', brand_id: 18, category_id: 1},
                               {id: 16, name: 'Aquaracer', brand_id: 6, category_id: 3},
                               {id: 61, name: 'Bamboo shopper真皮圆筒包', brand_id: 12, category_id: 1},
                               {id: 73, name: 'Medium horseferry check bowling', brand_id: 15, category_id: 1},
                               {id: 80, name: 'Bamboo shopper真皮圆筒包', brand_id: 12, category_id: 1},
                               {id: 75, name: 'Miss Dior', brand_id: 16, category_id: 1},
                               {id: 76, name: 'Saffiano leather tote', brand_id: 17, category_id: 1},
                               {id: 74, name: 'Lady Dior ', brand_id: 16, category_id: 1},
                               {id: 2, name: 'Jypsière - GM', brand_id: 1, category_id: 1},
                               {id: 27, name: 'De Ville Ladymatic 34 mm', brand_id: 5, category_id: 3},
                               {id: 53, name: 'Seamaster Diver 41 mm', brand_id: 5, category_id: 3},
                               {id: 81, name: 'Bamboo leather backpack', brand_id: 12, category_id: 1},
                               {id: 62, name: 'Bamboo shopper leather tote', brand_id: 12, category_id: 1},
                               {id: 25, name: 'Soya', brand_id: 1, category_id: 9}
                           ])

puts "#{products.count} products created"


pricings = Pricing.create!([
                               {id: 523, from_city_id: '9', to_city_id: 7, product_id: 73, saving_in_from_currency: 346.0},
                               {id: 407, from_city_id: '9', to_city_id: 15, product_id: 62, saving_in_from_currency: 410.0},
                               {id: 433, from_city_id: '9', to_city_id: 17, product_id: 76, saving_in_from_currency: 840.0},
                               {id: 133, from_city_id: '6', to_city_id: 4, product_id: 23, saving_in_from_currency: -830.0},
                               {id: 520, from_city_id: '9', to_city_id: 16, product_id: 73, saving_in_from_currency: 390.0},
                               {id: 409, from_city_id: '9', to_city_id: 16, product_id: 62, saving_in_from_currency: 415.0},
                               {id: 428, from_city_id: '9', to_city_id: 14, product_id: 76, saving_in_from_currency: 628.0},
                               {id: 513, from_city_id: '10', to_city_id: 14, product_id: 89, saving_in_from_currency: 1121.0},
                               {id: 514, from_city_id: '10', to_city_id: 14, product_id: 88, saving_in_from_currency: 556.0},
                               {id: 511, from_city_id: '10', to_city_id: 2, product_id: 89, saving_in_from_currency: 1692.0},
                               {id: 131, from_city_id: '6', to_city_id: 1, product_id: 32, saving_in_from_currency: 854.0},
                               {id: 495, from_city_id: '10', to_city_id: 2, product_id: 88, saving_in_from_currency: 846.0},
                               {id: 524, from_city_id: '9', to_city_id: 11, product_id: 74, saving_in_from_currency: 1965.0},
                               {id: 271, from_city_id: '6', to_city_id: 7, product_id: 5, saving_in_from_currency: 73.0},
                               {id: 499, from_city_id: '10', to_city_id: 7, product_id: 88, saving_in_from_currency: 601.0},
                               {id: 500, from_city_id: '10', to_city_id: 1, product_id: 88, saving_in_from_currency: 601.0},
                               {id: 32, from_city_id: '6', to_city_id: 2, product_id: 8, saving_in_from_currency: 579.0},
                               {id: 501, from_city_id: '10', to_city_id: 2, product_id: 86, saving_in_from_currency: 1260.0},
                               {id: 494, from_city_id: '10', to_city_id: 2, product_id: 85, saving_in_from_currency: 1068.0},
                               {id: 19, from_city_id: '6', to_city_id: 1, product_id: 5, saving_in_from_currency: 73.0},
                               {id: 148, from_city_id: '6', to_city_id: 1, product_id: 37, saving_in_from_currency: 169.0},
                               {id: 294, from_city_id: '6', to_city_id: 7, product_id: 58, saving_in_from_currency: 128.0},
                               {id: 7, from_city_id: '6', to_city_id: 1, product_id: 3, saving_in_from_currency: 208.0},
                               {id: 293, from_city_id: '6', to_city_id: 7, product_id: 41, saving_in_from_currency: 574.0},
                               {id: 517, from_city_id: '9', to_city_id: 2, product_id: 73, saving_in_from_currency: 1166.0},
                               {id: 418, from_city_id: '9', to_city_id: 14, product_id: 68, saving_in_from_currency: 783.0},
                               {id: 471, from_city_id: '9', to_city_id: 14, product_id: 61, saving_in_from_currency: 262.0},
                               {id: 255, from_city_id: '6', to_city_id: 7, product_id: 17, saving_in_from_currency: 256.0},
                               {id: 28, from_city_id: '6', to_city_id: 1, product_id: 7, saving_in_from_currency: 140.0},
                               {id: 301, from_city_id: '6', to_city_id: 8, product_id: 10, saving_in_from_currency: -937.0},
                               {id: 76, from_city_id: '6', to_city_id: 4, product_id: 16, saving_in_from_currency: -860.0},
                               {id: 518, from_city_id: '9', to_city_id: 11, product_id: 73, saving_in_from_currency: 1166.0},
                               {id: 515, from_city_id: '10', to_city_id: 14, product_id: 87, saving_in_from_currency: 696.0},
                               {id: 510, from_city_id: '10', to_city_id: 8, product_id: 87, saving_in_from_currency: -58.0},
                               {id: 272, from_city_id: '6', to_city_id: 7, product_id: 40, saving_in_from_currency: 98.0},
                               {id: 509, from_city_id: '10', to_city_id: 4, product_id: 87, saving_in_from_currency: -58.0},
                               {id: 504, from_city_id: '10', to_city_id: 8, product_id: 86, saving_in_from_currency: -226.0},
                               {id: 496, from_city_id: '10', to_city_id: 11, product_id: 88, saving_in_from_currency: 846.0},
                               {id: 512, from_city_id: '10', to_city_id: 11, product_id: 89, saving_in_from_currency: 1692.0},
                               {id: 503, from_city_id: '10', to_city_id: 4, product_id: 86, saving_in_from_currency: -226.0},
                               {id: 498, from_city_id: '10', to_city_id: 8, product_id: 88, saving_in_from_currency: -33.0},
                               {id: 497, from_city_id: '10', to_city_id: 4, product_id: 88, saving_in_from_currency: -33.0},
                               {id: 353, from_city_id: '6', to_city_id: 8, product_id: 19, saving_in_from_currency: -1753.0},
                               {id: 332, from_city_id: '6', to_city_id: 8, product_id: 11, saving_in_from_currency: -937.0},
                               {id: 46, from_city_id: '6', to_city_id: 4, product_id: 10, saving_in_from_currency: -937.0},
                               {id: 312, from_city_id: '6', to_city_id: 8, product_id: 10, saving_in_from_currency: -937.0},
                               {id: 140, from_city_id: '6', to_city_id: 4, product_id: 35, saving_in_from_currency: -385.0},
                               {id: 519, from_city_id: '9', to_city_id: 17, product_id: 73, saving_in_from_currency: 404.0},
                               {id: 134, from_city_id: '6', to_city_id: 4, product_id: 33, saving_in_from_currency: -357.0},
                               {id: 525, from_city_id: '9', to_city_id: 11, product_id: 91, saving_in_from_currency: 1965.0},
                               {id: 257, from_city_id: '6', to_city_id: 7, product_id: 25, saving_in_from_currency: 139.0},
                               {id: 196, from_city_id: '6', to_city_id: 1, product_id: 53, saving_in_from_currency: 332.0},
                               {id: 64, from_city_id: '6', to_city_id: 1, product_id: 14, saving_in_from_currency: 635.0},
                               {id: 516, from_city_id: '10', to_city_id: 14, product_id: 86, saving_in_from_currency: 816.0},
                               {id: 116, from_city_id: '6', to_city_id: 1, product_id: 27, saving_in_from_currency: 2395.0},
                               {id: 502, from_city_id: '10', to_city_id: 11, product_id: 86, saving_in_from_currency: 1260.0},
                               {id: 505, from_city_id: '10', to_city_id: 7, product_id: 86, saving_in_from_currency: 892.0},
                               {id: 221, from_city_id: '6', to_city_id: 7, product_id: 23, saving_in_from_currency: 73.0},
                               {id: 252, from_city_id: '6', to_city_id: 7, product_id: 18, saving_in_from_currency: 324.0},
                               {id: 191, from_city_id: '6', to_city_id: 4, product_id: 52, saving_in_from_currency: -1013.0},
                               {id: 56, from_city_id: '6', to_city_id: 4, product_id: 12, saving_in_from_currency: -675.0},
                               {id: 232, from_city_id: '6', to_city_id: 7, product_id: 7, saving_in_from_currency: 140.0},
                               {id: 44, from_city_id: '6', to_city_id: 1, product_id: 10, saving_in_from_currency: 229.0},
                               {id: 521, from_city_id: '9', to_city_id: 4, product_id: 73, saving_in_from_currency: -102.0},
                               {id: 282, from_city_id: '6', to_city_id: 7, product_id: 54, saving_in_from_currency: 134.0},
                               {id: 373, from_city_id: '6', to_city_id: 8, product_id: 49, saving_in_from_currency: -2683.0},
                               {id: 371, from_city_id: '6', to_city_id: 8, product_id: 54, saving_in_from_currency: -411.0},
                               {id: 369, from_city_id: '6', to_city_id: 8, product_id: 59, saving_in_from_currency: -590.0},
                               {id: 368, from_city_id: '6', to_city_id: 8, product_id: 60, saving_in_from_currency: -621.0},
                               {id: 350, from_city_id: '6', to_city_id: 8, product_id: 37, saving_in_from_currency: -516.0},
                               {id: 349, from_city_id: '6', to_city_id: 8, product_id: 35, saving_in_from_currency: -385.0},
                               {id: 347, from_city_id: '6', to_city_id: 8, product_id: 20, saving_in_from_currency: -1753.0},
                               {id: 339, from_city_id: '6', to_city_id: 8, product_id: 5, saving_in_from_currency: -830.0},
                               {id: 334, from_city_id: '6', to_city_id: 8, product_id: 28, saving_in_from_currency: -1436.0},
                               {id: 13, from_city_id: '6', to_city_id: 1, product_id: 4, saving_in_from_currency: 106.0},
                               {id: 65, from_city_id: '6', to_city_id: 4, product_id: 14, saving_in_from_currency: -3602.0},
                               {id: 66, from_city_id: '6', to_city_id: 4, product_id: 14, saving_in_from_currency: -3602.0},
                               {id: 346, from_city_id: '6', to_city_id: 8, product_id: 12, saving_in_from_currency: -675.0},
                               {id: 185, from_city_id: '6', to_city_id: 4, product_id: 50, saving_in_from_currency: -846.0},
                               {id: 149, from_city_id: '6', to_city_id: 4, product_id: 38, saving_in_from_currency: -436.0},
                               {id: 113, from_city_id: '6', to_city_id: 4, product_id: 26, saving_in_from_currency: -846.0},
                               {id: 522, from_city_id: '9', to_city_id: 8, product_id: 73, saving_in_from_currency: -102.0},
                               {id: 217, from_city_id: '6', to_city_id: 1, product_id: 60, saving_in_from_currency: 204.0},
                               {id: 450, from_city_id: '13', to_city_id: 4, product_id: 75, saving_in_from_currency: -128.0},
                               {id: 367, from_city_id: '6', to_city_id: 8, product_id: 57, saving_in_from_currency: -288.0},
                               {id: 362, from_city_id: '6', to_city_id: 8, product_id: 45, saving_in_from_currency: -4124.0},
                               {id: 262, from_city_id: '6', to_city_id: 7, product_id: 8, saving_in_from_currency: 127.0},
                               {id: 361, from_city_id: '6', to_city_id: 8, product_id: 46, saving_in_from_currency: -3869.0},
                               {id: 352, from_city_id: '6', to_city_id: 8, product_id: 22, saving_in_from_currency: -830.0},
                               {id: 326, from_city_id: '6', to_city_id: 8, product_id: 5, saving_in_from_currency: -830.0},
                               {id: 173, from_city_id: '6', to_city_id: 4, product_id: 46, saving_in_from_currency: -3869.0},
                               {id: 152, from_city_id: '6', to_city_id: 4, product_id: 39, saving_in_from_currency: -375.0},
                               {id: 137, from_city_id: '6', to_city_id: 4, product_id: 34, saving_in_from_currency: -882.0},
                               {id: 151, from_city_id: '6', to_city_id: 1, product_id: 38, saving_in_from_currency: 142.0},
                               {id: 136, from_city_id: '6', to_city_id: 1, product_id: 33, saving_in_from_currency: 116.0},
                               {id: 284, from_city_id: '6', to_city_id: 7, product_id: 50, saving_in_from_currency: 277.0},
                               {id: 256, from_city_id: '6', to_city_id: 7, product_id: 24, saving_in_from_currency: 106.0},
                               {id: 508, from_city_id: '10', to_city_id: 11, product_id: 87, saving_in_from_currency: 1092.0},
                               {id: 260, from_city_id: '6', to_city_id: 7, product_id: 3, saving_in_from_currency: 208.0},
                               {id: 214, from_city_id: '6', to_city_id: 1, product_id: 59, saving_in_from_currency: 193.0},
                               {id: 261, from_city_id: '6', to_city_id: 7, product_id: 21, saving_in_from_currency: 73.0},
                               {id: 311, from_city_id: '6', to_city_id: 8, product_id: 7, saving_in_from_currency: -1304.0},
                               {id: 35, from_city_id: '6', to_city_id: 4, product_id: 8, saving_in_from_currency: -638.0},
                               {id: 506, from_city_id: '10', to_city_id: 1, product_id: 86, saving_in_from_currency: 892.0},
                               {id: 124, from_city_id: '6', to_city_id: 2, product_id: 30, saving_in_from_currency: 390.0},
                               {id: 57, from_city_id: '6', to_city_id: 2, product_id: 13, saving_in_from_currency: 1404.0},
                               {id: 156, from_city_id: '6', to_city_id: 2, product_id: 40, saving_in_from_currency: 138.0},
                               {id: 507, from_city_id: '10', to_city_id: 2, product_id: 87, saving_in_from_currency: 1092.0},
                               {id: 39, from_city_id: '6', to_city_id: 1, product_id: 9, saving_in_from_currency: 81.0},
                               {id: 211, from_city_id: '6', to_city_id: 1, product_id: 58, saving_in_from_currency: 128.0},
                               {id: 48, from_city_id: '6', to_city_id: 1, product_id: 11, saving_in_from_currency: 139.0},
                               {id: 270, from_city_id: '6', to_city_id: 7, product_id: 32, saving_in_from_currency: 854.0},
                               {id: 268, from_city_id: '6', to_city_id: 7, product_id: 30, saving_in_from_currency: 277.0},
                               {id: 92, from_city_id: '6', to_city_id: 1, product_id: 19, saving_in_from_currency: 656.0},
                               {id: 83, from_city_id: '6', to_city_id: 1, product_id: 18, saving_in_from_currency: 324.0},
                               {id: 222, from_city_id: '6', to_city_id: 7, product_id: 9, saving_in_from_currency: 203.0},
                               {id: 50, from_city_id: '6', to_city_id: 4, product_id: 11, saving_in_from_currency: -937.0},
                               {id: 3, from_city_id: '6', to_city_id: 1, product_id: 2, saving_in_from_currency: 218.0},
                               {id: 286, from_city_id: '6', to_city_id: 7, product_id: 48, saving_in_from_currency: 311.0},
                               {id: 288, from_city_id: '6', to_city_id: 7, product_id: 46, saving_in_from_currency: 1292.0},
                               {id: 193, from_city_id: '6', to_city_id: 1, product_id: 52, saving_in_from_currency: 332.0},
                               {id: 26, from_city_id: '6', to_city_id: 4, product_id: 6, saving_in_from_currency: -1915.0},
                               {id: 238, from_city_id: '6', to_city_id: 7, product_id: 14, saving_in_from_currency: 635.0},
                               {id: 184, from_city_id: '6', to_city_id: 1, product_id: 49, saving_in_from_currency: 837.0},
                               {id: 15, from_city_id: '6', to_city_id: 4, product_id: 4, saving_in_from_currency: -678.0},
                               {id: 365, from_city_id: '6', to_city_id: 8, product_id: 42, saving_in_from_currency: -1116.0},
                               {id: 356, from_city_id: '6', to_city_id: 8, product_id: 53, saving_in_from_currency: -1013.0},
                               {id: 355, from_city_id: '6', to_city_id: 8, product_id: 55, saving_in_from_currency: -308.0},
                               {id: 351, from_city_id: '6', to_city_id: 8, product_id: 38, saving_in_from_currency: -436.0},
                               {id: 337, from_city_id: '6', to_city_id: 8, product_id: 31, saving_in_from_currency: -2604.0},
                               {id: 212, from_city_id: '6', to_city_id: 4, product_id: 59, saving_in_from_currency: -590.0},
                               {id: 123, from_city_id: '6', to_city_id: 4, product_id: 30, saving_in_from_currency: -846.0},
                               {id: 114, from_city_id: '6', to_city_id: 4, product_id: 27, saving_in_from_currency: -7901.0},
                               {id: 122, from_city_id: '6', to_city_id: 1, product_id: 29, saving_in_from_currency: 285.0},
                               {id: 94, from_city_id: '6', to_city_id: 4, product_id: 19, saving_in_from_currency: -1753.0},
                               {id: 63, from_city_id: '6', to_city_id: 1, product_id: 14, saving_in_from_currency: 635.0},
                               {id: 36, from_city_id: '6', to_city_id: 4, product_id: 8, saving_in_from_currency: -638.0},
                               {id: 40, from_city_id: '6', to_city_id: 4, product_id: 9, saving_in_from_currency: -687.0},
                               {id: 197, from_city_id: '6', to_city_id: 4, product_id: 54, saving_in_from_currency: -411.0},
                               {id: 263, from_city_id: '6', to_city_id: 7, product_id: 11, saving_in_from_currency: 139.0},
                               {id: 6, from_city_id: '6', to_city_id: 4, product_id: 2, saving_in_from_currency: -1753.0},
                               {id: 51, from_city_id: '6', to_city_id: 4, product_id: 11, saving_in_from_currency: -937.0},
                               {id: 285, from_city_id: '6', to_city_id: 7, product_id: 49, saving_in_from_currency: 837.0},
                               {id: 359, from_city_id: '6', to_city_id: 8, product_id: 48, saving_in_from_currency: -949.0},
                               {id: 358, from_city_id: '6', to_city_id: 8, product_id: 50, saving_in_from_currency: -846.0},
                               {id: 357, from_city_id: '6', to_city_id: 8, product_id: 51, saving_in_from_currency: -1180.0},
                               {id: 354, from_city_id: '6', to_city_id: 8, product_id: 21, saving_in_from_currency: -830.0},
                               {id: 331, from_city_id: '6', to_city_id: 8, product_id: 9, saving_in_from_currency: -687.0},
                               {id: 324, from_city_id: '6', to_city_id: 8, product_id: 24, saving_in_from_currency: -678.0},
                               {id: 322, from_city_id: '6', to_city_id: 8, product_id: 25, saving_in_from_currency: -937.0},
                               {id: 209, from_city_id: '6', to_city_id: 4, product_id: 58, saving_in_from_currency: -390.0},
                               {id: 206, from_city_id: '6', to_city_id: 4, product_id: 57, saving_in_from_currency: -288.0},
                               {id: 194, from_city_id: '6', to_city_id: 4, product_id: 53, saving_in_from_currency: -1013.0},
                               {id: 126, from_city_id: '6', to_city_id: 4, product_id: 31, saving_in_from_currency: -2604.0},
                               {id: 461, from_city_id: '9', to_city_id: 15, product_id: 65, saving_in_from_currency: 1311.0},
                               {id: 34, from_city_id: '6', to_city_id: 1, product_id: 8, saving_in_from_currency: 127.0},
                               {id: 70, from_city_id: '6', to_city_id: 4, product_id: 15, saving_in_from_currency: -1556.0},
                               {id: 241, from_city_id: '6', to_city_id: 7, product_id: 12, saving_in_from_currency: 126.0},
                               {id: 239, from_city_id: '6', to_city_id: 7, product_id: 2, saving_in_from_currency: 218.0},
                               {id: 220, from_city_id: '6', to_city_id: 7, product_id: 3, saving_in_from_currency: 208.0},
                               {id: 223, from_city_id: '6', to_city_id: 7, product_id: 5, saving_in_from_currency: 73.0},
                               {id: 300, from_city_id: '6', to_city_id: 7, product_id: 52, saving_in_from_currency: 332.0},
                               {id: 103, from_city_id: '6', to_city_id: 4, product_id: 22, saving_in_from_currency: -830.0},
                               {id: 43, from_city_id: '6', to_city_id: 1, product_id: 10, saving_in_from_currency: 229.0},
                               {id: 306, from_city_id: '6', to_city_id: 8, product_id: 13, saving_in_from_currency: -1761.0},
                               {id: 29, from_city_id: '6', to_city_id: 1, product_id: 7, saving_in_from_currency: 140.0},
                               {id: 4, from_city_id: '6', to_city_id: 1, product_id: 2, saving_in_from_currency: 218.0},
                               {id: 101, from_city_id: '6', to_city_id: 1, product_id: 22, saving_in_from_currency: 73.0},
                               {id: 249, from_city_id: '6', to_city_id: 7, product_id: 13, saving_in_from_currency: 313.0},
                               {id: 236, from_city_id: '6', to_city_id: 7, product_id: 7, saving_in_from_currency: 675.0},
                               {id: 97, from_city_id: '6', to_city_id: 4, product_id: 20, saving_in_from_currency: -1753.0},
                               {id: 219, from_city_id: '6', to_city_id: 7, product_id: 4, saving_in_from_currency: 106.0},
                               {id: 172, from_city_id: '6', to_city_id: 1, product_id: 45, saving_in_from_currency: 1337.0},
                               {id: 109, from_city_id: '6', to_city_id: 1, product_id: 25, saving_in_from_currency: 139.0},
                               {id: 318, from_city_id: '6', to_city_id: 8, product_id: 18, saving_in_from_currency: -1042.0},
                               {id: 459, from_city_id: '10', to_city_id: 15, product_id: 62, saving_in_from_currency: 237.0},
                               {id: 375, from_city_id: '6', to_city_id: 8, product_id: 3, saving_in_from_currency: -2130.0},
                               {id: 295, from_city_id: '6', to_city_id: 7, product_id: 57, saving_in_from_currency: 94.0},
                               {id: 366, from_city_id: '6', to_city_id: 8, product_id: 58, saving_in_from_currency: -390.0},
                               {id: 95, from_city_id: '6', to_city_id: 1, product_id: 20, saving_in_from_currency: 656.0},
                               {id: 296, from_city_id: '6', to_city_id: 7, product_id: 55, saving_in_from_currency: 100.0},
                               {id: 309, from_city_id: '6', to_city_id: 8, product_id: 15, saving_in_from_currency: -1556.0},
                               {id: 161, from_city_id: '6', to_city_id: 4, product_id: 42, saving_in_from_currency: -1116.0},
                               {id: 129, from_city_id: '6', to_city_id: 4, product_id: 32, saving_in_from_currency: -2643.0},
                               {id: 297, from_city_id: '6', to_city_id: 7, product_id: 60, saving_in_from_currency: 204.0},
                               {id: 224, from_city_id: '6', to_city_id: 7, product_id: 8, saving_in_from_currency: 59.0},
                               {id: 298, from_city_id: '6', to_city_id: 7, product_id: 59, saving_in_from_currency: 193.0},
                               {id: 290, from_city_id: '6', to_city_id: 7, product_id: 44, saving_in_from_currency: 357.0},
                               {id: 430, from_city_id: '9', to_city_id: 1, product_id: 76, saving_in_from_currency: 813.0},
                               {id: 432, from_city_id: '9', to_city_id: 16, product_id: 76, saving_in_from_currency: 813.0},
                               {id: 431, from_city_id: '9', to_city_id: 15, product_id: 76, saving_in_from_currency: 813.0},
                               {id: 399, from_city_id: '9', to_city_id: 1, product_id: 63, saving_in_from_currency: 1464.0},
                               {id: 402, from_city_id: '9', to_city_id: 17, product_id: 63, saving_in_from_currency: 617.0},
                               {id: 178, from_city_id: '6', to_city_id: 1, product_id: 47, saving_in_from_currency: 598.0},
                               {id: 71, from_city_id: '6', to_city_id: 4, product_id: 15, saving_in_from_currency: -1556.0},
                               {id: 253, from_city_id: '6', to_city_id: 7, product_id: 22, saving_in_from_currency: 73.0},
                               {id: 47, from_city_id: '6', to_city_id: 2, product_id: 11, saving_in_from_currency: 1113.0},
                               {id: 299, from_city_id: '6', to_city_id: 7, product_id: 56, saving_in_from_currency: 107.0},
                               {id: 250, from_city_id: '6', to_city_id: 7, product_id: 26, saving_in_from_currency: 277.0},
                               {id: 237, from_city_id: '6', to_city_id: 7, product_id: 19, saving_in_from_currency: 656.0},
                               {id: 45, from_city_id: '6', to_city_id: 4, product_id: 10, saving_in_from_currency: -937.0},
                               {id: 248, from_city_id: '6', to_city_id: 7, product_id: 20, saving_in_from_currency: 656.0},
                               {id: 128, from_city_id: '6', to_city_id: 1, product_id: 31, saving_in_from_currency: 864.0},
                               {id: 225, from_city_id: '6', to_city_id: 7, product_id: 10, saving_in_from_currency: 229.0},
                               {id: 100, from_city_id: '6', to_city_id: 4, product_id: 21, saving_in_from_currency: -830.0},
                               {id: 363, from_city_id: '6', to_city_id: 8, product_id: 44, saving_in_from_currency: -1090.0},
                               {id: 462, from_city_id: '9', to_city_id: 15, product_id: 66, saving_in_from_currency: 1458.0},
                               {id: 228, from_city_id: '6', to_city_id: 7, product_id: 12, saving_in_from_currency: 304.0},
                               {id: 84, from_city_id: '6', to_city_id: 1, product_id: 18, saving_in_from_currency: 324.0},
                               {id: 85, from_city_id: '6', to_city_id: 4, product_id: 18, saving_in_from_currency: -1042.0},
                               {id: 245, from_city_id: '6', to_city_id: 7, product_id: 2, saving_in_from_currency: 218.0},
                               {id: 11, from_city_id: '6', to_city_id: 4, product_id: 3, saving_in_from_currency: -2130.0},
                               {id: 86, from_city_id: '6', to_city_id: 4, product_id: 18, saving_in_from_currency: -1042.0},
                               {id: 283, from_city_id: '6', to_city_id: 7, product_id: 53, saving_in_from_currency: 332.0},
                               {id: 145, from_city_id: '6', to_city_id: 1, product_id: 36, saving_in_from_currency: 91.0},
                               {id: 389, from_city_id: '10', to_city_id: 17, product_id: 61, saving_in_from_currency: 253.0},
                               {id: 275, from_city_id: '6', to_city_id: 7, product_id: 39, saving_in_from_currency: 122.0},
                               {id: 280, from_city_id: '6', to_city_id: 7, product_id: 38, saving_in_from_currency: 142.0},
                               {id: 251, from_city_id: '6', to_city_id: 7, product_id: 18, saving_in_from_currency: 324.0},
                               {id: 279, from_city_id: '6', to_city_id: 7, product_id: 37, saving_in_from_currency: 169.0},
                               {id: 17, from_city_id: '6', to_city_id: 2, product_id: 5, saving_in_from_currency: 552.0},
                               {id: 316, from_city_id: '6', to_city_id: 8, product_id: 17, saving_in_from_currency: -539.0},
                               {id: 488, from_city_id: '9', to_city_id: 11, product_id: 70, saving_in_from_currency: 2184.0},
                               {id: 317, from_city_id: '6', to_city_id: 8, product_id: 17, saving_in_from_currency: -539.0},
                               {id: 2, from_city_id: '6', to_city_id: 2, product_id: 2, saving_in_from_currency: 5087.0},
                               {id: 146, from_city_id: '6', to_city_id: 4, product_id: 37, saving_in_from_currency: -516.0},
                               {id: 73, from_city_id: '6', to_city_id: 1, product_id: 16, saving_in_from_currency: 150.0},
                               {id: 491, from_city_id: '9', to_city_id: 2, product_id: 81, saving_in_from_currency: 1199.0},
                               {id: 135, from_city_id: '6', to_city_id: 2, product_id: 33, saving_in_from_currency: 164.0},
                               {id: 231, from_city_id: '6', to_city_id: 7, product_id: 6, saving_in_from_currency: 689.0},
                               {id: 125, from_city_id: '6', to_city_id: 1, product_id: 30, saving_in_from_currency: 277.0},
                               {id: 41, from_city_id: '6', to_city_id: 4, product_id: 9, saving_in_from_currency: -687.0},
                               {id: 429, from_city_id: '9', to_city_id: 7, product_id: 76, saving_in_from_currency: 747.0},
                               {id: 419, from_city_id: '9', to_city_id: 7, product_id: 68, saving_in_from_currency: 964.0},
                               {id: 93, from_city_id: '6', to_city_id: 2, product_id: 19, saving_in_from_currency: 5087.0},
                               {id: 52, from_city_id: '6', to_city_id: 2, product_id: 12, saving_in_from_currency: 366.0},
                               {id: 67, from_city_id: '6', to_city_id: 2, product_id: 15, saving_in_from_currency: 2496.0},
                               {id: 413, from_city_id: '10', to_city_id: 7, product_id: 62, saving_in_from_currency: 201.0},
                               {id: 68, from_city_id: '6', to_city_id: 1, product_id: 15, saving_in_from_currency: 258.0},
                               {id: 49, from_city_id: '6', to_city_id: 1, product_id: 11, saving_in_from_currency: 139.0},
                               {id: 410, from_city_id: '10', to_city_id: 1, product_id: 62, saving_in_from_currency: 241.0},
                               {id: 177, from_city_id: '6', to_city_id: 2, product_id: 47, saving_in_from_currency: 840.0},
                               {id: 79, from_city_id: '6', to_city_id: 1, product_id: 17, saving_in_from_currency: 256.0},
                               {id: 417, from_city_id: '9', to_city_id: 2, product_id: 68, saving_in_from_currency: 2042.0},
                               {id: 403, from_city_id: '9', to_city_id: 15, product_id: 63, saving_in_from_currency: 580.0},
                               {id: 377, from_city_id: '9', to_city_id: 2, product_id: 61, saving_in_from_currency: 1263.0},
                               {id: 186, from_city_id: '6', to_city_id: 2, product_id: 50, saving_in_from_currency: 390.0},
                               {id: 62, from_city_id: '6', to_city_id: 2, product_id: 14, saving_in_from_currency: 1440.0},
                               {id: 106, from_city_id: '6', to_city_id: 1, product_id: 24, saving_in_from_currency: 106.0},
                               {id: 102, from_city_id: '6', to_city_id: 2, product_id: 22, saving_in_from_currency: 552.0},
                               {id: 165, from_city_id: '6', to_city_id: 2, product_id: 43, saving_in_from_currency: 402.0},
                               {id: 38, from_city_id: '6', to_city_id: 1, product_id: 9, saving_in_from_currency: 288.0},
                               {id: 336, from_city_id: '6', to_city_id: 8, product_id: 30, saving_in_from_currency: -846.0},
                               {id: 335, from_city_id: '6', to_city_id: 8, product_id: 29, saving_in_from_currency: -872.0},
                               {id: 179, from_city_id: '6', to_city_id: 4, product_id: 48, saving_in_from_currency: -949.0},
                               {id: 404, from_city_id: '9', to_city_id: 17, product_id: 62, saving_in_from_currency: 432.0},
                               {id: 390, from_city_id: '12', to_city_id: 1, product_id: 66, saving_in_from_currency: 1464.0},
                               {id: 393, from_city_id: '13', to_city_id: 1, product_id: 72, saving_in_from_currency: 712.0},
                               {id: 30, from_city_id: '6', to_city_id: 4, product_id: 7, saving_in_from_currency: -1304.0},
                               {id: 99, from_city_id: '6', to_city_id: 2, product_id: 21, saving_in_from_currency: 552.0},
                               {id: 475, from_city_id: '9', to_city_id: 15, product_id: 9, saving_in_from_currency: 974.0},
                               {id: 400, from_city_id: '9', to_city_id: 7, product_id: 63, saving_in_from_currency: 1350.0},
                               {id: 8, from_city_id: '6', to_city_id: 2, product_id: 3, saving_in_from_currency: 1283.0},
                               {id: 242, from_city_id: '6', to_city_id: 7, product_id: 15, saving_in_from_currency: 258.0},
                               {id: 411, from_city_id: '10', to_city_id: 2, product_id: 62, saving_in_from_currency: 865.0},
                               {id: 482, from_city_id: '10', to_city_id: 1, product_id: 70, saving_in_from_currency: 381.0},
                               {id: 138, from_city_id: '6', to_city_id: 2, product_id: 34, saving_in_from_currency: 407.0},
                               {id: 485, from_city_id: '10', to_city_id: 17, product_id: 70, saving_in_from_currency: 407.0},
                               {id: 479, from_city_id: '10', to_city_id: 11, product_id: 70, saving_in_from_currency: 1235.0},
                               {id: 435, from_city_id: '10', to_city_id: 7, product_id: 76, saving_in_from_currency: 307.0},
                               {id: 174, from_city_id: '6', to_city_id: 2, product_id: 46, saving_in_from_currency: 1792.0},
                               {id: 416, from_city_id: '10', to_city_id: 16, product_id: 62, saving_in_from_currency: 240.0},
                               {id: 473, from_city_id: '9', to_city_id: 2, product_id: 9, saving_in_from_currency: 1177.0},
                               {id: 202, from_city_id: '6', to_city_id: 1, product_id: 55, saving_in_from_currency: 100.0},
                               {id: 382, from_city_id: '9', to_city_id: 16, product_id: 61, saving_in_from_currency: 413.0},
                               {id: 376, from_city_id: '6', to_city_id: 8, product_id: 23, saving_in_from_currency: -830.0},
                               {id: 395, from_city_id: '12', to_city_id: 1, product_id: 67, saving_in_from_currency: 1122.0},
                               {id: 408, from_city_id: '9', to_city_id: 7, product_id: 62, saving_in_from_currency: 362.0},
                               {id: 477, from_city_id: '9', to_city_id: 17, product_id: 9, saving_in_from_currency: 1009.0},
                               {id: 458, from_city_id: '10', to_city_id: 15, product_id: 61, saving_in_from_currency: 240.0},
                               {id: 440, from_city_id: '9', to_city_id: 14, product_id: 77, saving_in_from_currency: 530.0},
                               {id: 121, from_city_id: '6', to_city_id: 2, product_id: 29, saving_in_from_currency: 402.0},
                               {id: 27, from_city_id: '6', to_city_id: 2, product_id: 7, saving_in_from_currency: 1057.0},
                               {id: 105, from_city_id: '6', to_city_id: 2, product_id: 24, saving_in_from_currency: 518.0},
                               {id: 112, from_city_id: '6', to_city_id: 2, product_id: 26, saving_in_from_currency: 390.0},
                               {id: 201, from_city_id: '6', to_city_id: 2, product_id: 55, saving_in_from_currency: 141.0},
                               {id: 492, from_city_id: '9', to_city_id: 2, product_id: 82, saving_in_from_currency: 2055.0},
                               {id: 424, from_city_id: '10', to_city_id: 7, product_id: 68, saving_in_from_currency: 352.0},
                               {id: 287, from_city_id: '6', to_city_id: 7, product_id: 47, saving_in_from_currency: 598.0},
                               {id: 446, from_city_id: '10', to_city_id: 14, product_id: 77, saving_in_from_currency: 193.0},
                               {id: 195, from_city_id: '6', to_city_id: 2, product_id: 53, saving_in_from_currency: 467.0},
                               {id: 397, from_city_id: '9', to_city_id: 2, product_id: 63, saving_in_from_currency: 2146.0},
                               {id: 330, from_city_id: '6', to_city_id: 8, product_id: 8, saving_in_from_currency: -638.0},
                               {id: 328, from_city_id: '6', to_city_id: 8, product_id: 6, saving_in_from_currency: -1915.0},
                               {id: 405, from_city_id: '9', to_city_id: 1, product_id: 62, saving_in_from_currency: 413.0},
                               {id: 204, from_city_id: '6', to_city_id: 2, product_id: 56, saving_in_from_currency: 153.0},
                               {id: 277, from_city_id: '6', to_city_id: 7, product_id: 34, saving_in_from_currency: 289.0},
                               {id: 276, from_city_id: '6', to_city_id: 7, product_id: 12, saving_in_from_currency: 126.0},
                               {id: 396, from_city_id: '13', to_city_id: 1, product_id: 73, saving_in_from_currency: 389.0},
                               {id: 278, from_city_id: '6', to_city_id: 7, product_id: 35, saving_in_from_currency: 125.0},
                               {id: 25, from_city_id: '6', to_city_id: 4, product_id: 6, saving_in_from_currency: -1915.0},
                               {id: 115, from_city_id: '6', to_city_id: 2, product_id: 27, saving_in_from_currency: 3467.0},
                               {id: 37, from_city_id: '6', to_city_id: 2, product_id: 9, saving_in_from_currency: 506.0},
                               {id: 157, from_city_id: '6', to_city_id: 1, product_id: 40, saving_in_from_currency: 98.0},
                               {id: 254, from_city_id: '6', to_city_id: 7, product_id: 17, saving_in_from_currency: 256.0},
                               {id: 308, from_city_id: '6', to_city_id: 8, product_id: 15, saving_in_from_currency: -1556.0},
                               {id: 229, from_city_id: '6', to_city_id: 7, product_id: 4, saving_in_from_currency: 106.0},
                               {id: 469, from_city_id: '9', to_city_id: 15, product_id: 76, saving_in_from_currency: 813.0},
                               {id: 203, from_city_id: '6', to_city_id: 4, product_id: 56, saving_in_from_currency: -1269.0},
                               {id: 323, from_city_id: '6', to_city_id: 8, product_id: 7, saving_in_from_currency: -1304.0},
                               {id: 142, from_city_id: '6', to_city_id: 1, product_id: 35, saving_in_from_currency: 125.0},
                               {id: 325, from_city_id: '6', to_city_id: 8, product_id: 9, saving_in_from_currency: -687.0},
                               {id: 476, from_city_id: '9', to_city_id: 16, product_id: 9, saving_in_from_currency: 983.0},
                               {id: 490, from_city_id: '9', to_city_id: 2, product_id: 80, saving_in_from_currency: 1263.0},
                               {id: 235, from_city_id: '2', to_city_id: 7, product_id: 2, saving_in_from_currency: 730.0},
                               {id: 381, from_city_id: '9', to_city_id: 15, product_id: 61, saving_in_from_currency: 413.0},
                               {id: 360, from_city_id: '6', to_city_id: 8, product_id: 47, saving_in_from_currency: -1821.0},
                               {id: 338, from_city_id: '6', to_city_id: 8, product_id: 32, saving_in_from_currency: -2643.0},
                               {id: 443, from_city_id: '9', to_city_id: 15, product_id: 77, saving_in_from_currency: 698.0},
                               {id: 465, from_city_id: '9', to_city_id: 15, product_id: 70, saving_in_from_currency: 1014.0},
                               {id: 394, from_city_id: '12', to_city_id: 1, product_id: 65, saving_in_from_currency: 1315.0},
                               {id: 385, from_city_id: '10', to_city_id: 11, product_id: 61, saving_in_from_currency: 865.0},
                               {id: 14, from_city_id: '6', to_city_id: 2, product_id: 4, saving_in_from_currency: 518.0},
                               {id: 480, from_city_id: '10', to_city_id: 14, product_id: 70, saving_in_from_currency: 173.0},
                               {id: 159, from_city_id: '6', to_city_id: 2, product_id: 41, saving_in_from_currency: 602.0},
                               {id: 493, from_city_id: '9', to_city_id: 2, product_id: 83, saving_in_from_currency: 1965.0},
                               {id: 160, from_city_id: '6', to_city_id: 1, product_id: 41, saving_in_from_currency: 574.0},
                               {id: 387, from_city_id: '10', to_city_id: 1, product_id: 61, saving_in_from_currency: 240.0},
                               {id: 98, from_city_id: '6', to_city_id: 1, product_id: 21, saving_in_from_currency: 73.0},
                               {id: 104, from_city_id: '6', to_city_id: 1, product_id: 23, saving_in_from_currency: 73.0},
                               {id: 240, from_city_id: '6', to_city_id: 7, product_id: 14, saving_in_from_currency: 635.0},
                               {id: 108, from_city_id: '6', to_city_id: 2, product_id: 25, saving_in_from_currency: 1113.0},
                               {id: 81, from_city_id: '6', to_city_id: 4, product_id: 17, saving_in_from_currency: -539.0},
                               {id: 420, from_city_id: '9', to_city_id: 1, product_id: 68, saving_in_from_currency: 1061.0},
                               {id: 218, from_city_id: '7', to_city_id: 2, product_id: 2, saving_in_from_currency: -4854.0},
                               {id: 259, from_city_id: '6', to_city_id: 7, product_id: 3, saving_in_from_currency: 743.0},
                               {id: 144, from_city_id: '6', to_city_id: 2, product_id: 36, saving_in_from_currency: 129.0},
                               {id: 87, from_city_id: '6', to_city_id: 1, product_id: 7, saving_in_from_currency: 742.0},
                               {id: 96, from_city_id: '6', to_city_id: 2, product_id: 20, saving_in_from_currency: 5087.0},
                               {id: 130, from_city_id: '6', to_city_id: 2, product_id: 32, saving_in_from_currency: 1255.0},
                               {id: 227, from_city_id: '6', to_city_id: 7, product_id: 2, saving_in_from_currency: 656.0},
                               {id: 199, from_city_id: '6', to_city_id: 1, product_id: 54, saving_in_from_currency: 134.0},
                               {id: 90, from_city_id: '6', to_city_id: 1, product_id: 7, saving_in_from_currency: 675.0},
                               {id: 171, from_city_id: '6', to_city_id: 2, product_id: 45, saving_in_from_currency: 1906.0},
                               {id: 127, from_city_id: '6', to_city_id: 2, product_id: 31, saving_in_from_currency: 1268.0},
                               {id: 216, from_city_id: '6', to_city_id: 2, product_id: 60, saving_in_from_currency: 286.0},
                               {id: 210, from_city_id: '6', to_city_id: 2, product_id: 58, saving_in_from_currency: 179.0},
                               {id: 91, from_city_id: '6', to_city_id: 1, product_id: 12, saving_in_from_currency: 304.0},
                               {id: 258, from_city_id: '6', to_city_id: 7, product_id: 7, saving_in_from_currency: 742.0},
                               {id: 437, from_city_id: '10', to_city_id: 16, product_id: 76, saving_in_from_currency: 354.0},
                               {id: 153, from_city_id: '6', to_city_id: 2, product_id: 39, saving_in_from_currency: 172.0},
                               {id: 427, from_city_id: '9', to_city_id: 2, product_id: 76, saving_in_from_currency: 1709.0},
                               {id: 307, from_city_id: '6', to_city_id: 8, product_id: 13, saving_in_from_currency: -1761.0},
                               {id: 164, from_city_id: '6', to_city_id: 4, product_id: 43, saving_in_from_currency: -872.0},
                               {id: 155, from_city_id: '6', to_city_id: 4, product_id: 40, saving_in_from_currency: -301.0},
                               {id: 457, from_city_id: '9', to_city_id: 17, product_id: 78, saving_in_from_currency: 735.0},
                               {id: 468, from_city_id: '9', to_city_id: 15, product_id: 72, saving_in_from_currency: 708.0},
                               {id: 463, from_city_id: '9', to_city_id: 15, product_id: 67, saving_in_from_currency: 1116.0},
                               {id: 466, from_city_id: '9', to_city_id: 15, product_id: 71, saving_in_from_currency: 1001.0},
                               {id: 370, from_city_id: '4', to_city_id: 8, product_id: 56, saving_in_from_currency: 155.0},
                               {id: 329, from_city_id: '6', to_city_id: 8, product_id: 8, saving_in_from_currency: -638.0},
                               {id: 9, from_city_id: '6', to_city_id: 1, product_id: 3, saving_in_from_currency: 208.0},
                               {id: 269, from_city_id: '6', to_city_id: 7, product_id: 31, saving_in_from_currency: 864.0},
                               {id: 489, from_city_id: '9', to_city_id: 14, product_id: 9, saving_in_from_currency: 760.0},
                               {id: 472, from_city_id: '9', to_city_id: 11, product_id: 76, saving_in_from_currency: 1709.0},
                               {id: 333, from_city_id: '6', to_city_id: 8, product_id: 26, saving_in_from_currency: -846.0},
                               {id: 314, from_city_id: '6', to_city_id: 8, product_id: 2, saving_in_from_currency: -1753.0},
                               {id: 53, from_city_id: '6', to_city_id: 1, product_id: 12, saving_in_from_currency: 126.0},
                               {id: 139, from_city_id: '6', to_city_id: 1, product_id: 34, saving_in_from_currency: 289.0},
                               {id: 378, from_city_id: '9', to_city_id: 11, product_id: 61, saving_in_from_currency: 1263.0},
                               {id: 447, from_city_id: '10', to_city_id: 1, product_id: 77, saving_in_from_currency: 433.0},
                               {id: 267, from_city_id: '6', to_city_id: 7, product_id: 29, saving_in_from_currency: 285.0},
                               {id: 175, from_city_id: '6', to_city_id: 1, product_id: 46, saving_in_from_currency: 1292.0},
                               {id: 61, from_city_id: '6', to_city_id: 4, product_id: 13, saving_in_from_currency: -1761.0},
                               {id: 176, from_city_id: '6', to_city_id: 4, product_id: 47, saving_in_from_currency: -1821.0},
                               {id: 158, from_city_id: '6', to_city_id: 4, product_id: 41, saving_in_from_currency: -1536.0},
                               {id: 60, from_city_id: '6', to_city_id: 4, product_id: 13, saving_in_from_currency: -1761.0},
                               {id: 384, from_city_id: '10', to_city_id: 2, product_id: 61, saving_in_from_currency: 865.0},
                               {id: 422, from_city_id: '9', to_city_id: 17, product_id: 68, saving_in_from_currency: 356.0},
                               {id: 421, from_city_id: '9', to_city_id: 15, product_id: 68, saving_in_from_currency: 327.0},
                               {id: 401, from_city_id: '9', to_city_id: 14, product_id: 63, saving_in_from_currency: 1134.0},
                               {id: 426, from_city_id: '10', to_city_id: 17, product_id: 68, saving_in_from_currency: 447.0},
                               {id: 82, from_city_id: '6', to_city_id: 2, product_id: 18, saving_in_from_currency: 871.0},
                               {id: 470, from_city_id: '10', to_city_id: 15, product_id: 76, saving_in_from_currency: 355.0},
                               {id: 388, from_city_id: '10', to_city_id: 16, product_id: 61, saving_in_from_currency: 240.0},
                               {id: 406, from_city_id: '9', to_city_id: 2, product_id: 62, saving_in_from_currency: 1265.0},
                               {id: 478, from_city_id: '10', to_city_id: 2, product_id: 70, saving_in_from_currency: 1235.0},
                               {id: 481, from_city_id: '10', to_city_id: 7, product_id: 70, saving_in_from_currency: 309.0},
                               {id: 460, from_city_id: '9', to_city_id: 15, product_id: 64, saving_in_from_currency: 1170.0},
                               {id: 484, from_city_id: '10', to_city_id: 16, product_id: 70, saving_in_from_currency: 381.0},
                               {id: 464, from_city_id: '9', to_city_id: 15, product_id: 69, saving_in_from_currency: 1016.0},
                               {id: 467, from_city_id: '9', to_city_id: 15, product_id: 73, saving_in_from_currency: 386.0},
                               {id: 305, from_city_id: '6', to_city_id: 8, product_id: 14, saving_in_from_currency: -3602.0},
                               {id: 247, from_city_id: '6', to_city_id: 7, product_id: 16, saving_in_from_currency: 150.0},
                               {id: 110, from_city_id: '6', to_city_id: 4, product_id: 25, saving_in_from_currency: -937.0},
                               {id: 233, from_city_id: '6', to_city_id: 7, product_id: 7, saving_in_from_currency: 140.0},
                               {id: 111, from_city_id: '6', to_city_id: 1, product_id: 26, saving_in_from_currency: 277.0},
                               {id: 150, from_city_id: '6', to_city_id: 2, product_id: 38, saving_in_from_currency: 201.0},
                               {id: 246, from_city_id: '6', to_city_id: 7, product_id: 16, saving_in_from_currency: 150.0},
                               {id: 243, from_city_id: '6', to_city_id: 7, product_id: 15, saving_in_from_currency: 258.0},
                               {id: 244, from_city_id: '6', to_city_id: 7, product_id: 13, saving_in_from_currency: 313.0},
                               {id: 483, from_city_id: '10', to_city_id: 15, product_id: 70, saving_in_from_currency: 374.0},
                               {id: 230, from_city_id: '6', to_city_id: 7, product_id: 6, saving_in_from_currency: 689.0},
                               {id: 89, from_city_id: '6', to_city_id: 1, product_id: 3, saving_in_from_currency: 743.0},
                               {id: 154, from_city_id: '6', to_city_id: 1, product_id: 39, saving_in_from_currency: 122.0},
                               {id: 486, from_city_id: '9', to_city_id: 14, product_id: 70, saving_in_from_currency: 739.0},
                               {id: 487, from_city_id: '9', to_city_id: 16, product_id: 70, saving_in_from_currency: 1023.0},
                               {id: 380, from_city_id: '9', to_city_id: 1, product_id: 61, saving_in_from_currency: 413.0},
                               {id: 273, from_city_id: '6', to_city_id: 7, product_id: 36, saving_in_from_currency: 91.0},
                               {id: 313, from_city_id: '6', to_city_id: 8, product_id: 4, saving_in_from_currency: -678.0},
                               {id: 303, from_city_id: '6', to_city_id: 8, product_id: 4, saving_in_from_currency: -678.0},
                               {id: 304, from_city_id: '6', to_city_id: 8, product_id: 14, saving_in_from_currency: -3602.0},
                               {id: 449, from_city_id: '13', to_city_id: 2, product_id: 74, saving_in_from_currency: 1965.0},
                               {id: 88, from_city_id: '6', to_city_id: 1, product_id: 2, saving_in_from_currency: 656.0},
                               {id: 10, from_city_id: '6', to_city_id: 4, product_id: 3, saving_in_from_currency: -2130.0},
                               {id: 143, from_city_id: '6', to_city_id: 4, product_id: 36, saving_in_from_currency: -281.0},
                               {id: 18, from_city_id: '6', to_city_id: 1, product_id: 5, saving_in_from_currency: 73.0},
                               {id: 383, from_city_id: '9', to_city_id: 17, product_id: 61, saving_in_from_currency: 431.0},
                               {id: 72, from_city_id: '6', to_city_id: 2, product_id: 16, saving_in_from_currency: 576.0},
                               {id: 386, from_city_id: '10', to_city_id: 7, product_id: 61, saving_in_from_currency: 201.0},
                               {id: 414, from_city_id: '10', to_city_id: 17, product_id: 62, saving_in_from_currency: 252.0},
                               {id: 315, from_city_id: '6', to_city_id: 8, product_id: 27, saving_in_from_currency: -7901.0},
                               {id: 310, from_city_id: '6', to_city_id: 8, product_id: 3, saving_in_from_currency: -2130.0},
                               {id: 302, from_city_id: '6', to_city_id: 8, product_id: 2, saving_in_from_currency: -1753.0},
                               {id: 215, from_city_id: '6', to_city_id: 4, product_id: 60, saving_in_from_currency: -621.0},
                               {id: 147, from_city_id: '6', to_city_id: 2, product_id: 37, saving_in_from_currency: 237.0},
                               {id: 434, from_city_id: '10', to_city_id: 2, product_id: 76, saving_in_from_currency: 1013.0},
                               {id: 425, from_city_id: '10', to_city_id: 1, product_id: 68, saving_in_from_currency: 424.0},
                               {id: 12, from_city_id: '6', to_city_id: 1, product_id: 4, saving_in_from_currency: 106.0},
                               {id: 379, from_city_id: '9', to_city_id: 7, product_id: 61, saving_in_from_currency: 360.0},
                               {id: 5, from_city_id: '6', to_city_id: 4, product_id: 2, saving_in_from_currency: -1753.0},
                               {id: 74, from_city_id: '6', to_city_id: 1, product_id: 16, saving_in_from_currency: 150.0},
                               {id: 107, from_city_id: '6', to_city_id: 4, product_id: 24, saving_in_from_currency: -678.0},
                               {id: 75, from_city_id: '6', to_city_id: 4, product_id: 16, saving_in_from_currency: -860.0},
                               {id: 16, from_city_id: '6', to_city_id: 4, product_id: 4, saving_in_from_currency: -678.0},
                               {id: 170, from_city_id: '6', to_city_id: 4, product_id: 45, saving_in_from_currency: -4124.0},
                               {id: 167, from_city_id: '6', to_city_id: 4, product_id: 44, saving_in_from_currency: -1090.0},
                               {id: 166, from_city_id: '6', to_city_id: 1, product_id: 43, saving_in_from_currency: 285.0},
                               {id: 168, from_city_id: '6', to_city_id: 2, product_id: 44, saving_in_from_currency: 502.0},
                               {id: 226, from_city_id: '6', to_city_id: 7, product_id: 9, saving_in_from_currency: 81.0},
                               {id: 80, from_city_id: '6', to_city_id: 4, product_id: 17, saving_in_from_currency: -539.0},
                               {id: 169, from_city_id: '6', to_city_id: 1, product_id: 44, saving_in_from_currency: 357.0},
                               {id: 474, from_city_id: '9', to_city_id: 11, product_id: 9, saving_in_from_currency: 1177.0},
                               {id: 445, from_city_id: '9', to_city_id: 17, product_id: 77, saving_in_from_currency: 265.0},
                               {id: 213, from_city_id: '6', to_city_id: 2, product_id: 59, saving_in_from_currency: 272.0},
                               {id: 33, from_city_id: '6', to_city_id: 1, product_id: 8, saving_in_from_currency: 59.0},
                               {id: 348, from_city_id: '6', to_city_id: 8, product_id: 34, saving_in_from_currency: -882.0},
                               {id: 120, from_city_id: '6', to_city_id: 4, product_id: 29, saving_in_from_currency: -872.0},
                               {id: 281, from_city_id: '6', to_city_id: 7, product_id: 51, saving_in_from_currency: 387.0},
                               {id: 372, from_city_id: '6', to_city_id: 8, product_id: 52, saving_in_from_currency: -1013.0},
                               {id: 321, from_city_id: '6', to_city_id: 8, product_id: 16, saving_in_from_currency: -860.0},
                               {id: 319, from_city_id: '6', to_city_id: 8, product_id: 18, saving_in_from_currency: -1042.0},
                               {id: 291, from_city_id: '6', to_city_id: 7, product_id: 43, saving_in_from_currency: 285.0},
                               {id: 200, from_city_id: '6', to_city_id: 4, product_id: 55, saving_in_from_currency: -308.0},
                               {id: 162, from_city_id: '6', to_city_id: 2, product_id: 42, saving_in_from_currency: 514.0},
                               {id: 292, from_city_id: '6', to_city_id: 7, product_id: 42, saving_in_from_currency: 365.0},
                               {id: 163, from_city_id: '6', to_city_id: 1, product_id: 42, saving_in_from_currency: 365.0},
                               {id: 327, from_city_id: '6', to_city_id: 8, product_id: 6, saving_in_from_currency: -1915.0},
                               {id: 320, from_city_id: '6', to_city_id: 8, product_id: 16, saving_in_from_currency: -860.0},
                               {id: 234, from_city_id: '6', to_city_id: 7, product_id: 10, saving_in_from_currency: 229.0},
                               {id: 182, from_city_id: '6', to_city_id: 4, product_id: 49, saving_in_from_currency: -2683.0},
                               {id: 198, from_city_id: '6', to_city_id: 2, product_id: 54, saving_in_from_currency: 189.0},
                               {id: 448, from_city_id: '10', to_city_id: 17, product_id: 77, saving_in_from_currency: 335.0},
                               {id: 180, from_city_id: '6', to_city_id: 2, product_id: 48, saving_in_from_currency: 437.0},
                               {id: 42, from_city_id: '6', to_city_id: 2, product_id: 10, saving_in_from_currency: 1113.0},
                               {id: 181, from_city_id: '6', to_city_id: 1, product_id: 48, saving_in_from_currency: 311.0},
                               {id: 265, from_city_id: '6', to_city_id: 7, product_id: 27, saving_in_from_currency: 2395.0},
                               {id: 266, from_city_id: '6', to_city_id: 7, product_id: 28, saving_in_from_currency: 471.0},
                               {id: 436, from_city_id: '10', to_city_id: 1, product_id: 76, saving_in_from_currency: 354.0},
                               {id: 54, from_city_id: '6', to_city_id: 1, product_id: 12, saving_in_from_currency: 126.0},
                               {id: 183, from_city_id: '6', to_city_id: 2, product_id: 49, saving_in_from_currency: 1275.0},
                               {id: 189, from_city_id: '6', to_city_id: 2, product_id: 51, saving_in_from_currency: 544.0},
                               {id: 187, from_city_id: '6', to_city_id: 1, product_id: 50, saving_in_from_currency: 277.0},
                               {id: 207, from_city_id: '6', to_city_id: 2, product_id: 57, saving_in_from_currency: 132.0},
                               {id: 55, from_city_id: '6', to_city_id: 4, product_id: 12, saving_in_from_currency: -675.0},
                               {id: 21, from_city_id: '6', to_city_id: 4, product_id: 5, saving_in_from_currency: -830.0},
                               {id: 374, from_city_id: '6', to_city_id: 8, product_id: 40, saving_in_from_currency: -301.0},
                               {id: 444, from_city_id: '9', to_city_id: 16, product_id: 77, saving_in_from_currency: 250.0},
                               {id: 31, from_city_id: '6', to_city_id: 4, product_id: 7, saving_in_from_currency: -1304.0},
                               {id: 119, from_city_id: '6', to_city_id: 1, product_id: 28, saving_in_from_currency: 471.0},
                               {id: 264, from_city_id: '6', to_city_id: 7, product_id: 11, saving_in_from_currency: 139.0},
                               {id: 289, from_city_id: '6', to_city_id: 7, product_id: 45, saving_in_from_currency: 1337.0},
                               {id: 439, from_city_id: '9', to_city_id: 2, product_id: 77, saving_in_from_currency: 1560.0},
                               {id: 208, from_city_id: '6', to_city_id: 1, product_id: 57, saving_in_from_currency: 94.0},
                               {id: 456, from_city_id: '9', to_city_id: 15, product_id: 78, saving_in_from_currency: 716.0},
                               {id: 455, from_city_id: '9', to_city_id: 1, product_id: 78, saving_in_from_currency: 718.0},
                               {id: 190, from_city_id: '6', to_city_id: 1, product_id: 51, saving_in_from_currency: 387.0},
                               {id: 205, from_city_id: '6', to_city_id: 1, product_id: 56, saving_in_from_currency: 107.0},
                               {id: 192, from_city_id: '6', to_city_id: 2, product_id: 52, saving_in_from_currency: 467.0},
                               {id: 188, from_city_id: '6', to_city_id: 4, product_id: 51, saving_in_from_currency: -1180.0},
                               {id: 423, from_city_id: '10', to_city_id: 2, product_id: 68, saving_in_from_currency: 1146.0},
                               {id: 141, from_city_id: '6', to_city_id: 2, product_id: 35, saving_in_from_currency: 177.0},
                               {id: 69, from_city_id: '6', to_city_id: 1, product_id: 15, saving_in_from_currency: 258.0},
                               {id: 132, from_city_id: '6', to_city_id: 2, product_id: 23, saving_in_from_currency: 552.0},
                               {id: 78, from_city_id: '6', to_city_id: 1, product_id: 17, saving_in_from_currency: 256.0},
                               {id: 77, from_city_id: '6', to_city_id: 2, product_id: 17, saving_in_from_currency: 267.0},
                               {id: 118, from_city_id: '6', to_city_id: 2, product_id: 28, saving_in_from_currency: 662.0},
                               {id: 58, from_city_id: '6', to_city_id: 1, product_id: 13, saving_in_from_currency: 313.0},
                               {id: 1, from_city_id: '2', to_city_id: 1, product_id: 2, saving_in_from_currency: 730.0},
                               {id: 59, from_city_id: '6', to_city_id: 1, product_id: 13, saving_in_from_currency: 313.0},
                               {id: 364, from_city_id: '6', to_city_id: 8, product_id: 43, saving_in_from_currency: -872.0},
                               {id: 117, from_city_id: '6', to_city_id: 4, product_id: 28, saving_in_from_currency: -1436.0},
                               {id: 274, from_city_id: '6', to_city_id: 7, product_id: 33, saving_in_from_currency: 116.0},
                               {id: 345, from_city_id: '6', to_city_id: 8, product_id: 12, saving_in_from_currency: -675.0},
                               {id: 22, from_city_id: '6', to_city_id: 2, product_id: 6, saving_in_from_currency: 1140.0},
                               {id: 23, from_city_id: '6', to_city_id: 1, product_id: 6, saving_in_from_currency: 689.0},
                               {id: 24, from_city_id: '6', to_city_id: 1, product_id: 6, saving_in_from_currency: 689.0},
                               {id: 20, from_city_id: '6', to_city_id: 4, product_id: 5, saving_in_from_currency: -830.0},
                               {id: 344, from_city_id: '6', to_city_id: 8, product_id: 11, saving_in_from_currency: -937.0},
                               {id: 341, from_city_id: '6', to_city_id: 8, product_id: 41, saving_in_from_currency: -1536.0},
                               {id: 342, from_city_id: '6', to_city_id: 8, product_id: 36, saving_in_from_currency: -281.0},
                               {id: 343, from_city_id: '6', to_city_id: 8, product_id: 39, saving_in_from_currency: -375.0},
                               {id: 340, from_city_id: '6', to_city_id: 8, product_id: 33, saving_in_from_currency: -357.0},
                               {id: 454, from_city_id: '9', to_city_id: 7, product_id: 78, saving_in_from_currency: 669.0},
                               {id: 441, from_city_id: '9', to_city_id: 7, product_id: 77, saving_in_from_currency: 642.0},
                               {id: 442, from_city_id: '9', to_city_id: 1, product_id: 77, saving_in_from_currency: 703.0},
                               {id: 438, from_city_id: '10', to_city_id: 17, product_id: 76, saving_in_from_currency: 371.0},
                               {id: 452, from_city_id: '9', to_city_id: 2, product_id: 78, saving_in_from_currency: 632.0},
                               {id: 451, from_city_id: '9', to_city_id: 11, product_id: 78, saving_in_from_currency: 632.0},
                               {id: 453, from_city_id: '9', to_city_id: 14, product_id: 78, saving_in_from_currency: 581.0}
                           ])


puts "#{pricings.count} pricings created"